# Site settings
title: Personal Website
description: A blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Thach Phung
user_description: Making things up as I go.
user_title: Software Developer
email: tba
github_username:  tba

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
